spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
aws:
  s3:
    bucket-name: footballmanager-bucket
    region: eu-central-1
  credentials:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}


cognito:

logging:
  level:
    org.springframework.security: DEBUG # Увімкнення повного рівня дебагу для Spring Security
    org.springframework.security.oauth2: DEBUG # Додатковий дебаг для роботи з токенами Oauth2
    com.yourpackage: DEBUG # Замініть "com.yourpackage" на корінний пакет вашого додатку, якщо хочете дебажити логіку API
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG # Вивід HTTP-запитів у логах